npm install @martip/node-red-pdf-to-png@1.0.1
npm install node-red-contrib-duckdb@0.0.7
npm install node-red-contrib-whatsapp-link@0.1.25
npm install node-red-contrib-telegrambot-home@0.7.2
npm install @yuliqi/node-red-mydb@0.0.6
npm install node-red-contrib-fasac@0.1.0
npm install node-red-contrib-meross@2.1.0
npm install @kevingodell/node-red-ffmpeg@0.1.1-beta.3
npm install @kevingodell/node-red-mp4frag@0.1.1-beta.1
npm install node-red-contrib-timer@1.0.4
